import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignIn } from "@clerk/nextjs";
import StoreProvider from "./StoreProvider";
import { dark, neobrutalism , shadesOfPurple } from '@clerk/themes'
import { AlertTriangle } from "lucide-react";

import ClientProvider from "./ClientProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-amber-100 border-b border-amber-200 py-2 px-4 text-center">
          <div className="max-w-7xl mx-auto flex items-center justify-center gap-2 text-amber-800">
            <AlertTriangle className="w-5 h-5 flex-shrink-0" />
            <p className="text-sm font-medium">
              This website is currently in prototype phase. You may encounter bugs, glitches, and performance issues. A production-ready version is under development.
            </p>
          </div>
        </div>
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}